import Head from "next/head";
import styled, { keyframes } from "styled-components";

const fadeIn = keyframes`
  from {
    filter: blur(10px);
  }
  to {
    filter: blur(0px);
  }
`;

const fadeRight = keyframes`
  
  from {
    transform: translateX(160%);
  }
  to {
    transform: translateX(0);
  }
`;

const Hero = styled.div`
  background-image: url("images/watt-background.png");
  background-size: cover;
  background-repeat: no-repeat;
  background-position: 20%;
  height: 100vh;
  display: flex;
  animation: ${fadeIn} 1s ease-in-out;

  @media (max-width: 768px) {
  }
`;

const HeadingContainer = styled.div`
  display: flex;
  flex-direction: column;
  margin: 8.5rem 0 0 15%;
`;

const Heading = styled.h1`
  color: white;
  font-size: 3rem;
  font-weight: normal;
  animation: ${fadeRight} 2s ease-in-out;
`;

const HeadingMiddle = styled.h1`
  color: white;
  font-size: 3rem;
  font-weight: normal;
  animation: ${fadeRight} 2.25s ease-in-out;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Watt Doctor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <HeadingContainer>
          <Heading>Charger</Heading>
          <HeadingMiddle style={{ padding: "0 0 0 3rem" }}>
            Installation
          </HeadingMiddle>
          <Heading style={{ padding: "0 0 0 1rem" }}>Simplified</Heading>
        </HeadingContainer>
      </Hero>
    </>
  );
}
