import Head from "next/head";
import styled from "styled-components";

const Hero = styled.div`
  height: 80vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: white;
`;

const Heading = styled.h1`
  color: black;
  font-size: 3rem;
  font-weight: bold;
`;

export default function Services() {
  return (
    <>
      <Head>
        <title>Services Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Heading>Services</Heading>
      </Hero>
    </>
  );
}
